"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.1.7.
"""

import os
from pathlib import Path
from decouple import config
import dj_database_url

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# ============ ОСНОВНЫЕ НАСТРОЙКИ ============
SECRET_KEY = config('SECRET_KEY', default='django-insecure-&&+pzhqbsetsd88pg!uj(=!30msp-sh)wsbr8impz6i1*$!9l)')
DEBUG = config('DEBUG', default=True, cast=bool)

# Исправляем ALLOWED_HOSTS
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# ============ БАЗА ДАННЫХ ============
DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default='sqlite:///' + str(BASE_DIR / 'db.sqlite3')),
        conn_max_age=600,
        conn_health_checks=True,
    )
}
LANGUAGE_CODE = 'ru-ru'
# ============ EMAIL НАСТРОЙКИ ============
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='i-max8@yandex.ru')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='uqskmaatutlhzmie')
DEFAULT_FROM_EMAIL = config('EMAIL_HOST_USER', default='i-max8@yandex.ru')

# ============ SUPABASE НАСТРОЙКИ ============
SUPABASE_PROJECT_ID = 'etcczklqfqdsomasmfcg'
SUPABASE_BUCKET = 'psm-media'

# ============ СТАТИКА и МЕДИА ФАЙЛЫ ============

# Проверяем, отключен ли Supabase для статики (например, на Render)
DISABLE_SUPABASE_STORAGE = config('DISABLE_SUPABASE_STORAGE', default=False, cast=bool)

# ВСЕГДА используем локальную статику для админки, CSS, JS и т.д.
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "myapp" / "static",
]
# Медиафайлы (загруженные пользователем) — в Supabase
MEDIA_URL = f'https://{SUPABASE_PROJECT_ID}.supabase.co/storage/v1/object/public/{SUPABASE_BUCKET}/media/'
DEFAULT_FILE_STORAGE = 'mysite.rest_storage.MediaStorage'  # твой кастомный бэкенд

# WhiteNoise для статики в продакшене
STORAGES = {
    "default": {"BACKEND": "mysite.rest_storage.MediaStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}
# ============ WHITE NOISE ============
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Должен быть вторым
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

# ============ AUTHENTICATION ============
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ============ AXES ============
AXES_FAILURE_LIMIT = 3
AXES_COOLOFF_TIME = 1
AXES_RESET_ON_SUCCESS = True

# ============ LOGGING ============
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'myapp.admin': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'axes': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    },
}

if not DEBUG:
    LOGGING['handlers']['console'] = {
        'level': 'WARNING',
        'class': 'logging.StreamHandler',
    }
    for logger_name in ['boto3', 'botocore', 'storages', '__name__']:
        if logger_name not in LOGGING['loggers']:
            LOGGING['loggers'][logger_name] = {
                'handlers': ['console'],
                'level': 'WARNING',
                'propagate': True,
            }

# ============ APPLICATIONS ============
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'axes',
    'myapp',
]


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
JAZZMIN_SETTINGS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-navy",  # или "navbar-purple"
    "accent": "accent-primary",
    "navbar": "navbar-navy navbar-dark",  # или "navbar-indigo"
    "no_navbar_border": True,
    "sidebar": "sidebar-dark-navy",      # или "sidebar-dark-indigo"
    "custom_css": "myapp/css/admin-custom.css",
    "custom_js": "myapp/js/admin-custom.js",
    "site_title": "ПСМ Админка",
    "site_header": "ПромСпецМонтаж",
    "welcome_sign": "Добро пожаловать в панель управления",
    "copyright": "ООО «ПромСпецМонтаж»",
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["myapp", "auth", "contenttypes", "sessions"],

    # Цветовая схема (светлая)
    "theme": "flatly",  # или "cerulean", "cosmo", "lumen", "minty"
    "dark_mode_theme": None,  # отключаем тёмную тему

    # Логотип (опционально)
    "site_logo": "myapp/images/logo-admin.jpg",  # положите в static
    "login_logo": None,

    # Иконки для моделей (очень круто!)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "myapp.News": "fas fa-newspaper",
        "myapp.Work": "fas fa-building",
        "myapp.Employee": "fas fa-hard-hat",
    },
}
# ============ TEMPLATES ============
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'debug': DEBUG,
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# ============ PASSWORD VALIDATION ============
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ============ INTERNATIONALIZATION ============

TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============ ROOT URL CONFIG ============
ROOT_URLCONF = 'mysite.urls'