# Generated by Django 5.1.7 on 2025-04-17 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_news_options_alter_newsimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'сообщения'},
        ),
    ]
