# Generated by Django 5.1.7 on 2025-12-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_testimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestImage',
        ),
    ]
