# Generated by Django 5.1.7 on 2025-03-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='phone',
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
