# Generated by Django 5.1.7 on 2025-03-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('photo', models.ImageField(upload_to='works/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='Информация')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Наши работы',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
