# Generated by Django 5.1.7 on 2025-03-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_newsimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsimage',
            options={'verbose_name': 'Изображение новости', 'verbose_name_plural': 'Изображения новостей'},
        ),
    ]
