# Generated by Django 5.1.7 on 2025-04-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_application_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название объекта'),
        ),
    ]
